#!/bin/bash
# Quick setup script for GitHub Secrets
# Instructions for configuring Snyk, GitGuardian, and SonarQube tokens

echo "========================================="
echo "GitHub Secrets Configuration Guide"
echo "========================================="
echo ""
echo "This script provides instructions for setting up GitHub secrets."
echo "You need to manually create accounts and add secrets via GitHub UI."
echo ""
echo "Steps:"
echo ""
echo "1. SNYK_TOKEN Configuration:"
echo "   - Go to: https://app.snyk.io/account/settings/targets"
echo "   - Copy your API Token"
echo "   - Go to: https://github.com/Kimou9/dependability-project-final/settings/secrets/actions"
echo "   - Click 'New repository secret'"
echo "   - Name: SNYK_TOKEN"
echo "   - Paste the token"
echo ""
echo "2. GITGUARDIAN_API_KEY Configuration:"
echo "   - Go to: https://dashboard.gitguardian.com/account/api-tokens"
echo "   - Create a new API token"
echo "   - Copy the token"
echo "   - Go to: GitHub Secrets"
echo "   - Click 'New repository secret'"
echo "   - Name: GITGUARDIAN_API_KEY"
echo "   - Paste the token"
echo ""
echo "3. SONAR_TOKEN Configuration:"
echo "   - Go to: https://sonarcloud.io/account/security/"
echo "   - Generate a new token (name it: github-actions)"
echo "   - Copy the token"
echo "   - Go to: GitHub Secrets"
echo "   - Click 'New repository secret'"
echo "   - Name: SONAR_TOKEN"
echo "   - Paste the token"
echo ""
echo "4. Verify Secrets Are Added:"
echo "   - Go to: https://github.com/Kimou9/dependability-project-final/settings/secrets/actions"
echo "   - You should see 3 secrets (without showing their values)"
echo ""
echo "5. Trigger Workflows:"
echo "   - Go to: https://github.com/Kimou9/dependability-project-final/actions"
echo "   - Select workflow"
echo "   - Click 'Run workflow'"
echo ""
echo "========================================="
